### ISSUE TITLE
How to learn the joints linear regressor J(·) for your self-defined joints of body?

### ISSUE THREAD

**Issue by luwang03** [2017211801/SemanticHuman#4]
How to learn the joints linear regressor J(·) for your self-defined joints of body? For your defined additional joints for feet, hands, and faces, how to learn the joints linear regressor J(·) ?
 
![image](https://github.com/2017211801/SemanticHuman/assets/26894064/66419350-8e07-4f85-bc9d-e2bd82443b2b)

**Comment by 2017211801** [comment]
We visualize the human body mesh in meshlab, and manually select landmark points, and then take the mean of these points as the final joint point position.

**Comment by luwang03** [comment]
Ok, thanks for your reply! From your reply,  the process of my understanding is that:
1) we can visualize template body mesh in meshlab and manually select landmark points on template body mesh;
2) next, for other body mesh, we can use the indexes of selected landmark in 1) to obtain the crrosponding landmark points and take the mean of these points as the final joint point position;
3) for all body joint points data, we can train a joints linear regressor J(·).
Is this understanding  is right?

**Comment by 2017211801** [comment]
There is no need for the third step, because the joint regressor is essentially a matrix. With the index of the landmark point, we can build the joint regressor. For example, the landmark point index of the 33rd joint point is [1000, 1001, 1002, 1003 ,1004], then you only need to change the corresponding value of the matrix to 1/5.

**Comment by luwang03** [comment]
That is great! Thanks for your reply!
